server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/events/**

        - id: auth-service-ui
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/register, /login, /index, /logout

        - id: auth-service-api
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka