server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    loadbalancer:
      enabled: true
    gateway:
      routes:
        - id: event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/events/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2

        - id: registration-service
          uri: lb://REGISTRATION-SERVICE
          predicates:
            - Path=/api/registrations/**
          filters:
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
